// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator
using Newtonsoft.Json;

namespace NugetUpdateV4
{

    internal class Xml
    {

        [JsonProperty("@version")]
        public string Version { get; set; }

        [JsonProperty("@encoding")]
        public string Encoding { get; set; }
    }

    public class Metadata
    {

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("version")]
        public string Version { get; set; }

    }

    internal class Package
    {

        [JsonProperty("@xmlns")]
        public string Xmlns { get; set; }

        [JsonProperty("metadata")]
        public Metadata Metadata { get; set; }
    }

    internal class ClassNuspec
    {

        [JsonProperty("?xml")]
        public Xml Xml { get; set; }

        [JsonProperty("package")]
        public Package Package { get; set; }
    }

}
